name: SoSimple
description: A sample web application
dependencies:
  polymer: any
  browser: any
  js: any
  route: any
  unittest: any
transformers:
- polymer:
    entry_points:
    - web/polymer.html

